<?php
// Prevent any output before JSON response
ob_start();

// Disable error display, log errors instead
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('log_errors', 1);

session_start();
require_once 'config.php';

// Clear any output that might have been generated by config.php
ob_clean();

header('Content-Type: application/json');

// Check if admin is logged in
if (!isset($_SESSION['admin_id'])) {
    echo json_encode(['success' => false, 'message' => 'Unauthorized access']);
    exit;
}

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    echo json_encode(['success' => false, 'message' => 'Invalid request method']);
    exit;
}

$input = json_decode(file_get_contents('php://input'), true);
$teacherId = $input['teacher_id'] ?? null;

if (!$teacherId) {
    echo json_encode(['success' => false, 'message' => 'Teacher ID is required']);
    exit;
}

try {
    // Check if approval_status column exists, if not use status column
    $stmt = $pdo->prepare("SHOW COLUMNS FROM teachers LIKE 'approval_status'");
    $stmt->execute();
    $hasApprovalStatus = $stmt->rowCount() > 0;
    
    $statusColumn = $hasApprovalStatus ? 'approval_status' : 'status';
    
    $pdo->beginTransaction();
    
    // Get teacher details before approval
    $stmt = $pdo->prepare("
        SELECT id, first_name, last_name, email, teacher_id 
        FROM teachers 
        WHERE id = ? AND {$statusColumn} = 'pending'
    ");
    $stmt->execute([$teacherId]);
    $teacher = $stmt->fetch(PDO::FETCH_ASSOC);
    
    if (!$teacher) {
        $pdo->rollBack();
        echo json_encode(['success' => false, 'message' => 'Teacher not found or already processed']);
        exit;
    }
    
    // Update teacher approval status
    $stmt = $pdo->prepare("
        UPDATE teachers 
        SET {$statusColumn} = 'approved', 
            approved_by = ?, 
            approved_at = NOW() 
        WHERE id = ? AND {$statusColumn} = 'pending'
    ");
    $stmt->execute([$_SESSION['admin_id'], $teacherId]);
    
    // Log admin activity
    $stmt = $pdo->prepare("
        INSERT INTO admin_activity_log (admin_id, action, target_type, target_id, details, ip_address, user_agent) 
        VALUES (?, 'approve_teacher', 'teacher', ?, ?, ?, ?)
    ");
    $stmt->execute([
        $_SESSION['admin_id'],
        $teacherId,
        "Teacher account approved: {$teacher['first_name']} {$teacher['last_name']} ({$teacher['email']})",
        $_SERVER['REMOTE_ADDR'] ?? 'unknown',
        $_SERVER['HTTP_USER_AGENT'] ?? 'unknown'
    ]);
    
    // Log teacher activity
    try {
        $pdo->exec("
            CREATE TABLE IF NOT EXISTS teacher_activity_log (
                id INT AUTO_INCREMENT PRIMARY KEY,
                teacher_id INT NOT NULL,
                action VARCHAR(100) NOT NULL,
                details TEXT,
                ip_address VARCHAR(45),
                user_agent TEXT,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                INDEX idx_teacher (teacher_id),
                INDEX idx_action (action),
                INDEX idx_created (created_at)
            )
        ");
        
        $stmt = $pdo->prepare("
            INSERT INTO teacher_activity_log (teacher_id, action, details, ip_address, user_agent)
            VALUES (?, 'account_approved', 'Account approved by admin', ?, ?)
        ");
        $stmt->execute([
            $teacherId,
            $_SERVER['REMOTE_ADDR'] ?? 'unknown',
            $_SERVER['HTTP_USER_AGENT'] ?? 'unknown'
        ]);
    } catch (Exception $e) {
        error_log("Failed to log teacher activity: " . $e->getMessage());
    }
    
    // Send approval email to teacher
    // Include Gmail verification function for email sending
    require_once __DIR__ . '/../gmail-fixed-test.php';
    
    $email_subject = "Your MathEase Teacher Account Has Been Approved";
    $email_body = "
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset='UTF-8'>
        <style>
            body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
            .container { max-width: 600px; margin: 0 auto; padding: 20px; }
            .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
            .content { background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px; }
            .button { display: inline-block; padding: 12px 30px; background: #667eea; color: white; text-decoration: none; border-radius: 5px; margin: 20px 0; }
            .footer { text-align: center; margin-top: 20px; color: #666; font-size: 12px; }
        </style>
    </head>
    <body>
        <div class='container'>
            <div class='header'>
                <h1>MathEase Teacher Portal</h1>
            </div>
            <div class='content'>
                <h2>Account Approved!</h2>
                <p>Hello {$teacher['first_name']} {$teacher['last_name']},</p>
                <p>Great news! Your MathEase teacher account has been approved by the administrator.</p>
                <p>You can now log in to your teacher dashboard and start using MathEase.</p>
                <div style='text-align: center;'>
                    <a href='" . (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https' : 'http') . "://" . $_SERVER['HTTP_HOST'] . dirname($_SERVER['PHP_SELF']) . "/../teacher-login.html' class='button'>Login to Dashboard</a>
                </div>
                <p>If you have any questions, please contact the administrator.</p>
            </div>
            <div class='footer'>
                <p>&copy; " . date('Y') . " MathEase. All rights reserved.</p>
            </div>
        </div>
    </body>
    </html>";
    
    // Use Gmail SMTP for sending approval email
    $email_sent = send_gmail_verification_fixed($teacher['email'], $email_subject, $email_body);
    
    // If Gmail fails, save to file as backup
    if (!$email_sent) {
        $file_result = save_email_to_file($teacher['email'], $email_subject, $email_body);
        error_log("Gmail SMTP failed for teacher approval email to {$teacher['email']}, saved to file: " . ($file_result ? 'Yes' : 'No'));
        // Still consider it successful if saved to file
        $email_sent = $file_result;
    } else {
        error_log("Teacher approval email sent successfully via Gmail to: {$teacher['email']}");
    }
    
    $pdo->commit();
    
    // Clear any output before sending JSON
    ob_clean();
    
    echo json_encode([
        'success' => true,
        'message' => 'Teacher account approved successfully. Approval email ' . ($email_sent ? 'sent' : 'failed to send') . '.',
        'email_sent' => $email_sent
    ]);
    ob_end_flush();
    exit;
    
} catch (Exception $e) {
    if (isset($pdo) && $pdo->inTransaction()) {
        $pdo->rollBack();
    }
    error_log("Admin approve teacher error: " . $e->getMessage());
    
    // Clear any output before sending JSON error
    ob_clean();
    
    echo json_encode([
        'success' => false,
        'message' => 'Failed to approve teacher: ' . $e->getMessage()
    ]);
    ob_end_flush();
    exit;
} catch (Error $e) {
    if (isset($pdo) && $pdo->inTransaction()) {
        $pdo->rollBack();
    }
    error_log("Admin approve teacher fatal error: " . $e->getMessage());
    
    // Clear any output before sending JSON error
    ob_clean();
    
    echo json_encode([
        'success' => false,
        'message' => 'A fatal server error occurred while approving teacher'
    ]);
    ob_end_flush();
    exit;
}
?>
